// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLGab3uLQa6OxCScmAg_mVzsgnytT5d1E',
    appId: '1:623296499746:web:057e0bf95e4ef325867a7b',
    messagingSenderId: '623296499746',
    projectId: 'dormitoryplatform',
    authDomain: 'dormitoryplatform.firebaseapp.com',
    storageBucket: 'dormitoryplatform.firebasestorage.app',
    measurementId: 'G-JBZNV3FH8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPUbOwzjqh5kzkAiyktUo_NAwft4i0jdw',
    appId: '1:623296499746:android:5a081657b5e3e025867a7b',
    messagingSenderId: '623296499746',
    projectId: 'dormitoryplatform',
    storageBucket: 'dormitoryplatform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlyM30MknhsJnsVEY_2VqdAld2HRbdoQE',
    appId: '1:623296499746:ios:975027cc30341be8867a7b',
    messagingSenderId: '623296499746',
    projectId: 'dormitoryplatform',
    storageBucket: 'dormitoryplatform.firebasestorage.app',
    iosClientId: '623296499746-cuglolodrmdjafbs4gbdt1kn5cg64q28.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlyM30MknhsJnsVEY_2VqdAld2HRbdoQE',
    appId: '1:623296499746:ios:975027cc30341be8867a7b',
    messagingSenderId: '623296499746',
    projectId: 'dormitoryplatform',
    storageBucket: 'dormitoryplatform.firebasestorage.app',
    iosClientId: '623296499746-cuglolodrmdjafbs4gbdt1kn5cg64q28.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLGab3uLQa6OxCScmAg_mVzsgnytT5d1E',
    appId: '1:623296499746:web:e7ae63b1f15e29fb867a7b',
    messagingSenderId: '623296499746',
    projectId: 'dormitoryplatform',
    authDomain: 'dormitoryplatform.firebaseapp.com',
    storageBucket: 'dormitoryplatform.firebasestorage.app',
    measurementId: 'G-23MCV1B4Z0',
  );

}