version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dorm_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: MyDorm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: dorm_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db          # **ต้องใช้ชื่อ service db เพราะ backend อยู่ใน network เดียวกับ db**
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: MyDorm
      PORT: 3000
    volumes:
      - .:/usr/src/app
    command: npm run start

volumes:
  pgdata:
